### ISSUE TITLE
Issue tracker for web app

### ISSUE THREAD

**Issue by hankhank10** [odwdinc/Python-SimConnect#21]
- Autopilot on/off buttons (except master) turn settings on but not off
- Autopilot set variable buttons do not work
- Autopilot airspeed variable not displaying
- Flaps slider displays wrong way round
- Trim data not working

**Comment by odwdinc** [comment]
Can you prove the events and or requests you are using all test them out.

**Comment by odwdinc** [comment]
> * ~~Autopilot on/off buttons (except master) turn settings on but not off~~  fixed
> * ~~Autopilot set variable buttons do not work~~ fixed   [Airspeed and the 2nd Attitude] are not fixed
> * Autopilot airspeed variable not displaying
> * Flaps slider displays wrong way round
> * Trim data not working

**Comment by hankhank10** [comment]
Thanks for these fixes.

I've identified the cause of the other outstanding issues and am working on fixes - will update once tested.

Perhaps it would be helpful to set up a project board to allow issues to be tracked in a more structured way?

**Comment by hankhank10** [comment]
All of these items should now be fixed in the latest PR. Please leave the issue open as I will raise new bugs as I find them here.

**Comment by odwdinc** [comment]
looks good, still not 100% on Airspeed AP bit where on the G1000 will this show?

**Comment by hankhank10** [comment]
I’ve only got it visible on the 747 so far - not all a/c will have all
settings

**Comment by odwdinc** [comment]
Ahh ok, Thanks, I have been testing with the Cessna 172 Skyhawk (G1000)
All check out with the 747

**Comment by odwdinc** [comment]
closing as work is moved off this repo.
